[project]
name = "llm-memory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aider-chat>=0.60.1",
    "httpx>=0.27.2",
]
